return {
	descriptions = {},
	misc = {
		achievement_descriptions = {},
		achievement_names = {},
		blind_states = {},
		challenge_names = {
			c_ina_glasses_team = "Glasses Team",
			c_ina_love_pair = "The Love Pair",
			c_ina_futbol_frontier = "Football Frontier",
			c_ina_elementals = "The Elementals",
			c_ina_more_or_less = "More or Less",
			c_ina_mark_challenge = "The Legendary goalkeeper",
			c_ina_recruiter = "Recruiter",
		},
		collabs = {},
		dictionary = {
			ina_evolve_level = "Level up!",
			ina_evolve_success = "Swap!",
			ina_val_down = "Drained!",
			ina_training = "Change!",
			ina_next_match = "Next",
			k_team_pack = "Team Pack",
			k_item_pack = "Item Pack",
			k_manager_pack = "Manager Pack",
			ina_convert = "Converted!",
			ina_potential_increased = "Potential increased!",
			ina_sell_increased = "Jokers improved!",
			ina_divine = "Divine Power!",
			ina_settings_custom_middle_blinds = "Custom blinds",
			ina_settings_middle_blinds_abilities = "Small and Big Blinds with abilities",
			ina_settings_winners_jokers = "Winning mod tournaments jokers",
			ina_settings_oc_jokers = "Jokers made by the community",
			ina_destroy = "Destroyed!",
			ina_dribbling = "Dribble!",
			ina_harvest = "Harvest!",
			ina_seed = "Sow!",
			ina_special_technique = "Super Techniques",
			ina_technique_upgrade = "Technique upgraded",
			ina_special_manager = "Managers",
			ina_manager_info = "Manager",
			ina_Fire = "Fire",
			ina_Forest = "Forest",
			ina_Wind = "Wind",
			ina_Mountain = "Mountain",
			ina_FW = "Forward",
			ina_MF = "Midfielder",
			ina_DF = "Defender",
			ina_GK = "Goalkeeper",
			ina_Technique = "Fusion",
			ina_bench = "Bench",
			ina_unbench = "Starter",
			ina_generate_barriers = "Barrier!",
			ina_onfire = "On fire!",
			ina_onwind = "Riding the wind!",
			ina_onforest = "In the woods!",
			ina_onmountain = "Unshakable as stone!",
			ina_gafas = "GLASSSES",
			ina_saved = "You were saved",
			ina_technique_card = "Technique!",
			ina_gol = "Goal!",
			ina_mano = "Hand enhanced",
			ina_akihiro = "Wait a little more, please",

			-- Rarity
			k_ina_top = "Top",
			k_ina_winner = "Winner",

			-- Rates
			ina_rates = "Rates",
			ina_jokers = "Jokers",
			ina_booster = "Boosters",
			ina_rates_pool = "Pool",
			ina_rates_available = "Available",
			ina_rates_rarity = "Rarity",
			ina_rates_count = "Count",
			ina_rates_weight = "Weight",
			ina_rates_chance = "Chance",
			ina_rates_base_packs = "Base Packs",
			ina_rates_total = "Total weight",

			-- Resources
			ina_resource_barriers = "Barriers",
			ina_training_upgrades = "Training",
			ina_forms = "Forms",
			ina_team = "Team",

			-- Credits menu
			ina_credits = "Credits",
			ina_thanks = "Thanks To",
			ina_lead_developer = "Main Developer: ",
			ina_graphic_designers = "Graphic Designers: ",
			ina_developers = "Developers: ",
		},
		high_scores = {},
		labels = {
			ina_training_seal = "Training Seal",
			ina_harvest_sticker = "Harvestable",
			ina_tech_plus1_sticker = "Upgraded Technique",
			ina_tech_plus2_sticker = "Upgraded Technique",
			ina_tech_plus3_sticker = "Upgraded Technique",
			ina_tech_plus4_sticker = "Upgraded Technique",
			ina_tech_plus5_sticker = "Upgraded Technique",
			ina_tech_number2_sticker = "Upgraded Technique",
			ina_tech_number3_sticker = "Upgraded Technique",
			ina_tech_number4_sticker = "Upgraded Technique",
			ina_tech_numbera_sticker = "Upgraded Technique",
			ina_tech_numbers_sticker = "Upgraded Technique",
			ina_tech_numberz_sticker = "Upgraded Technique",
			ina_tech_numberinf_sticker = "Upgraded Technique",
			ina_tech_grade2_sticker = "Upgraded Technique",
			ina_tech_grade3_sticker = "Upgraded Technique",
			ina_tech_grade4_sticker = "Upgraded Technique",
			ina_tech_grade5_sticker = "Upgraded Technique",
			ina_tech_grade0_sticker = "Upgraded Technique",
			ina_tech_j_sticker = "Upgraded Technique",
			ina_tech_q_sticker = "Upgraded Technique",
			ina_tech_k_sticker = "Upgraded Technique",
			ina_tech_a_sticker = "Upgraded Technique",
			ina_tech_joker_sticker = "Upgraded Technique",

			k_ina_top = "Top",
			k_ina_winner = "Winner",
		},
		poker_hand_descriptions = {
			["ina_TriplePair"] = {
				"3 different pairs",
			},
			["ina_FullMansion"] = {
				"2 different Three of a Kinds",
			},
			["ina_GodHand"] = {
				"6 cards of the same rank"
			}
		},
		poker_hands = {
			["ina_TriplePair"] = "Triple pair",
			["ina_FullMansion"] = "Full Mansion",
			["ina_GodHand"] = "God Hand",
		},
		quips = {},
		ranks = {},
		suits_plural = {},
		suits_singular = {},
		tutorial = {},
		v_dictionary = {
			a_powmult = { "^#1# Mult" },
			ina_idea = { "Idea: #1#" },
			ina_art = { "Art: #1#" },
			ina_code = { "Code: #1#" }
		},
		v_text = {
			ch_c_ina_futbol_frontier = { "Blinds will be in {C:attention}Fútbol Frontier{} order" },
			ch_c_ina_win_ante16 = { "Defeat a {C:dark_edition}Legendary{} enemy" },
			ch_c_ina_elementals = { "Blinds can only be {C:dark_edition}Elemental{}" }
		}
	}
}
