return {
    misc = {
        achievement_descriptions = {},
        achievement_names = {},
        blind_states = {},
        challenge_names = {
            c_ina_glasses_team = "Equipo Gafas",
            c_ina_love_pair = "La Pareja del Amor",
            c_ina_futbol_frontier = "Futbol Frontier",
            c_ina_elementals = "Los Elementales",
            c_ina_more_or_less = "Mas o Menos",
            c_ina_mark_challenge = "El portero legendario",
            c_ina_recruiter = "Fichatron",
        },
        collabs = {},
        dictionary = {
            ina_evolve_level = "¡Nivel subido!",
            ina_evolve_success = "¡Intercambio!",
            ina_val_down = "¡Drenado!",
            ina_training = "¡Cambio!",
            ina_next_match = "Siguiente",
            k_team_pack = "Pack de Equipo",
            k_item_pack = "Pack de Objetos",
            k_manager_pack = "Pack de Managers",
            ina_convert = "¡Convertido!",
            ina_potential_increased = "¡Potencial aumentado!",
            ina_sell_increased = "¡Jokers mejorados!",
            ina_divine = "¡Poder Divino!",
            ina_settings_custom_middle_blinds = "Ciegas personalizadas",
            ina_settings_middle_blinds_abilities = "Ciegas Pequeñas y Grandes con habilidades",
            ina_settings_winners_jokers = "Jokers Ganadores de Torneo",
            ina_settings_oc_jokers = "Jokers creados por la comunidad",
            ina_destroy = "¡Destruido!",
            ina_dribbling = "¡Regate!",
            ina_harvest = "Cosecha!",
            ina_seed = "Siembra!",
            ina_special_technique = "Super Técnicas",
            ina_technique_upgrade = "Técnica mejorada",
            ina_special_manager = "Gerentes",
            ina_manager_info = "Gerente",
            ina_Fire = "Fuego",
            ina_Forest = "Bosque",
            ina_Wind = "Viento",
            ina_Mountain = "Montaña",
            ina_FW = "Delantero",
            ina_MF = "Mediocentro",
            ina_DF = "Defensa",
            ina_GK = "Portero",
            ina_Technique = "Fusión",
            ina_bench = "Banquillo",
            ina_unbench = "Titular",
            ina_generate_barriers = "Barrera!",
            ina_onfire = "On fire!",
            ina_onwind = "Riding the wind!",
            ina_onforest = "In the woods!",
            ina_onmountain = "Unshakable as stone!",
            ina_gafas = "GAFITAAAS",
            ina_saved = "Fuiste salvado",
            ina_technique_card = "¡Técnica!",
            ina_gol = "¡Gol!",
            ina_mano = "¡Mano mejorada",

            -- Rarities
            k_ina_top = "Destacado",
            k_ina_winner = "Ganador",

            -- Rates
            ina_rates = "Probabilidades",
            ina_jokers = "Jokers",
            ina_booster = "Paquetes de Refuerzo",
            ina_rates_pool = "Pool",
            ina_rates_available = "Disponibles",
            ina_rates_rarity = "Rareza",
            ina_rates_count = "Cantidad",
            ina_rates_weight = "Peso",
            ina_rates_chance = "Prob.",
            ina_rates_base_packs = "Paquetes Base",
            ina_rates_total = "Peso total",

            -- Resources
            ina_resource_barriers = "Barreras",
            ina_training_upgrades = "Entrenamiento",
            ina_forms = "Formas",
            ina_team = "Equipo",

            -- Credits menu
            ina_credits = "Créditos",
            ina_thanks = "Gracias a",
            ina_lead_developer = "Desarrollador principal: ",
            ina_graphic_designers = "Diseñadores: ",
            ina_developers = "Desarrolladores: ",
            ina_akihiro = "Por favor, espere un poco más"
        },
        high_scores = {},
        labels = {
            ina_training_seal = "Sello Entrenamiento",
            ina_harvest_sticker = "Cosechable",
            ina_tech_plus1_sticker = "Técnica mejorada",
            ina_tech_plus2_sticker = "Técnica mejorada",
            ina_tech_plus3_sticker = "Técnica mejorada",
            ina_tech_plus4_sticker = "Técnica mejorada",
            ina_tech_plus5_sticker = "Técnica mejorada",
            ina_tech_number2_sticker = "Técnica mejorada",
            ina_tech_number3_sticker = "Técnica mejorada",
            ina_tech_number4_sticker = "Técnica mejorada",
            ina_tech_numbera_sticker = "Técnica mejorada",
            ina_tech_numbers_sticker = "Técnica mejorada",
            ina_tech_numberz_sticker = "Técnica mejorada",
            ina_tech_numberinf_sticker = "Técnica mejorada",
            ina_tech_grade2_sticker = "Técnica mejorada",
            ina_tech_grade3_sticker = "Técnica mejorada",
            ina_tech_grade4_sticker = "Técnica mejorada",
            ina_tech_grade5_sticker = "Técnica mejorada",
            ina_tech_grade0_sticker = "Técnica mejorada",
            ina_tech_j_sticker = "Técnica mejorada",
            ina_tech_q_sticker = "Técnica mejorada",
            ina_tech_k_sticker = "Técnica mejorada",
            ina_tech_a_sticker = "Técnica mejorada",
            ina_tech_joker_sticker = "Técnica mejorada",

            k_ina_top = "Destacado",
            k_ina_winner = "Ganador",
        },
        poker_hand_descriptions = {
            ["ina_TriplePair"] = {
                "3 parejas distintas",
            },
            ["ina_FullMansion"] = {
                "2 Tríos distintos",
            },
            ["ina_GodHand"] = {
                "6 cartas del mismo rango"
            }
        },
        poker_hands = {
            ["ina_TriplePair"] = "Triple pareja",
            ["ina_FullMansion"] = "Full Mansion",
            ["ina_GodHand"] = "Mano Celestial",
        },
        quips = {},
        ranks = {},
        suits_plural = {},
        suits_singular = {},
        tutorial = {},
        v_dictionary = {
            a_powmult = { "^#1# Mult" },
            ina_idea = { "Idea: #1#" },
            ina_art = { "Arte: #1#" },
            ina_code = { "Código: #1#" }
        },
        v_text = {
            ch_c_ina_futbol_frontier = { "Las ciegas saldrán en el orden del {C:attention}Fútbol Frontier{}" },
            ch_c_ina_win_ante16 = { "Supera un enemigo {C:dark_edition}Legendario{}" },
            ch_c_ina_elementals = { "Las ciegas solo podrán ser {C:dark_edition}Elementales{}" }
        }
    }
}
